export const mockUsers = [
  {
    id: 1,
    username: 'admin',
    password: 'admin',
    name: 'สมชาย ผู้ดูแลระบบ',
    role: 'Admin',
    email: 'admin@jiratools.com',
    avatar: 'ส',
    department: 'IT Operations',
  },
  {
    id: 2,
    username: 'user',
    password: 'user',
    name: 'สมหญิง นักพัฒนา',
    role: 'User',
    email: 'user@jiratools.com',
    avatar: 'ห',
    department: 'Development',
  },
  {
    id: 3,
    username: 'somchai',
    password: 'pass123',
    name: 'สมศักดิ์ ทีมงาน',
    role: 'User',
    email: 'somchai@jiratools.com',
    avatar: 'ศ',
    department: 'QA',
  },
];
